import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <img src="https://www.freepngimg.com/thumb/world_wide_web/25084-6-world-wide-web-transparent-background.png" height={220} alt="img" />
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda nam exercitationem asperiores ipsa laboriosam. Eos quisquam ea tenetur, rerum consequuntur excepturi saepe debitis sunt cupiditate quas accusantium alias voluptatibus ratione unde iusto, error incidunt. Ratione nemo, tempora sed minus, placeat vel fuga molestiae expedita culpa officiis odit esse quisquam distinctio id asperiores commodi dolores laborum deserunt consectetur. Laudantium itaque dolor adipisci quasi quae quia alias accusamus illum, ad vitae! Quisquam quod corporis obcaecati, amet autem, et laborum tenetur dolorem architecto, delectus reprehenderit quos consectetur? Quibusdam minima esse molestiae modi beatae! Dolorum blanditiis delectus, optio eveniet ipsa sequi harum, at, neque repudiandae quia iste? Asperiores voluptate accusamus repellat eum similique, cupiditate ea qui deserunt nobis earum amet. Odit, aliquid voluptatum quisquam officia modi sapiente ex ducimus praesentium asperiores mollitia tenetur non neque sequi! Doloribus amet aut quia expedita consequuntur ipsa repellendus. Optio cupiditate ipsa maxime et numquam aperiam veritatis, esse repellendus, harum quod corrupti unde maiores obcaecati ea deserunt explicabo, incidunt dolore dolor totam! Sed repellat non quidem in. Quod error non magni atque voluptas harum assumenda itaque, delectus placeat unde ea nisi dolorem eius eum, quidem optio aut a officia odio, architecto deleniti cum inventore illum! Consectetur eius animi amet officia reprehenderit beatae sunt dignissimos provident quibusdam esse nisi magni, unde, magnam labore quas at facere assumenda autem repudiandae saepe alias? Animi cupiditate ab natus tenetur. Expedita ut doloribus, quas facilis, asperiores voluptatem doloremque id tempora rem itaque totam commodi suscipit possimus quis sequi! Autem officia a mollitia incidunt repudiandae?
        </p>
      </main>
    </>
  )
}
