import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis, totam iure! Vero nam, aperiam tempore provident facilis fugit ut beatae, dignissimos possimus quae sit consectetur iste dolor ipsam mollitia a nemo quisquam iure, incidunt esse placeat ipsa saepe magni quasi. Odio fuga dolores eligendi repellendus cum soluta esse tempora rerum culpa nisi amet, praesentium a placeat. Illum, fugiat enim! Quisquam labore odit ducimus minima nihil voluptate quo suscipit totam necessitatibus veniam id quidem saepe impedit a, expedita neque fugit repellat! Non nobis facere perferendis nemo, itaque nesciunt esse quaerat commodi sapiente, quam, voluptate tempora aspernatur nisi obcaecati veritatis? Natus corporis non consequatur fugit, dolorem delectus soluta corrupti debitis. Dolorum, nobis! Fuga blanditiis obcaecati, dolore facilis, similique natus rem hic excepturi accusamus tempore deserunt! Dolorem, impedit suscipit recusandae aut facere veniam, earum ea consequatur reiciendis, delectus quam commodi sed odio deserunt? Omnis voluptatibus velit nesciunt optio minus dolores quo consequatur culpa veniam cum adipisci voluptatum ex, laboriosam numquam sunt dignissimos quis, soluta repellendus expedita. Numquam, suscipit veniam adipisci placeat, impedit deserunt alias odio quisquam labore, assumenda porro! Aliquam sit culpa veniam reprehenderit minima, delectus, atque adipisci dolores quidem quam magni error nulla eum sint amet fugiat ab consequatur aut natus. Neque commodi deserunt harum, iusto culpa alias beatae odit pariatur mollitia aliquid laudantium. Adipisci esse temporibus perspiciatis blanditiis. Quasi saepe qui quia iusto voluptas sapiente quis! Nesciunt, in aliquid cum aspernatur fugit tenetur vel quis sapiente expedita at aliquam voluptate nemo beatae soluta quibusdam pariatur totam suscipit harum voluptates sit minima. Debitis velit rem inventore architecto accusantium, sint nobis ab, perferendis quidem, dolorum hic. Cupiditate quod officiis harum voluptatibus dolores totam dolore autem aperiam? Vero illo saepe, pariatur nisi natus fugiat expedita adipisci nobis voluptates odio. Rerum, deserunt sit ad magnam nam accusamus ea quos error natus ipsa expedita quibusdam illum saepe molestiae molestias pariatur dolores atque nihil, quo blanditiis sunt rem iste deleniti perspiciatis. Possimus voluptatum, nihil, reiciendis fugiat nisi, rem reprehenderit incidunt ut at optio repudiandae earum voluptates. At repellat quidem architecto laborum nulla? Similique, dolorem. Vitae, iure dolores facilis pariatur, eveniet velit libero laborum quibusdam commodi, vel quo. Totam quo molestias expedita consectetur tempore corporis, atque corrupti eligendi aut, iusto doloribus ut voluptatibus, aliquid laborum consequatur commodi explicabo amet architecto cupiditate quos libero! Distinctio quasi consequuntur accusantium corrupti earum nam, iure mollitia ipsum possimus, culpa eius tempora doloribus? Tenetur, excepturi, amet maiores eveniet error enim, expedita vero esse ut ipsum quaerat natus nostrum voluptates eos facilis sint perferendis aut fugiat animi suscipit possimus. Illo aliquam rem expedita blanditiis accusamus, eius odit voluptas deserunt iste nam earum repellendus eos obcaecati dicta quia vitae. Nisi, nostrum, expedita harum, laudantium et autem quisquam accusamus molestiae ducimus pariatur ad repellendus. Laudantium, nihil quis. Consequatur possimus dolor vel dignissimos quo minus molestiae doloremque delectus quasi aperiam nesciunt, aspernatur eos voluptates excepturi vitae. Aliquid veritatis voluptatibus dolores soluta maxime rem inventore quo! Autem odio minima reiciendis placeat dolore unde, omnis praesentium velit, rem dignissimos quibusdam quos eligendi voluptas vel eaque sunt necessitatibus error deleniti.
        </p>
      </main>
    </>
  )
}
